In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

import cleverhans

/home/xi/.virtualenvs/tf1/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/xi/.virtualenvs/tf1/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/xi/.virtualenvs/tf1/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/xi/.virtualenvs/tf1/lib/python3.6/site-packages/tensorflow/python/f

In [2]:
x = np.array([1, 2, 3, 4, 5])
x.shape

(5,)

In [3]:
np.clip(x, 2, 4)

array([2, 2, 3, 4, 4])

In [4]:
y = np.array([1, 2, 3, 4, 5, 6, 7, 8])
with tf.Session() as sess:
    print(sess.run(tf.clip_by_value(y, 3, 5)))


[3 3 3 4 5 5 5 5]


In [5]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

In [6]:
xr = x.reshape(1, 2, 3)
xr.shape

(1, 2, 3)

In [7]:
len(x)
xr.flatten()

array([1, 2, 3, 4, 5, 6])

In [8]:
y0 = np.zeros(shape=y.shape)
y0

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x2 = np.tile(x, (2, 1, 1))
x2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [10]:
x3 = np.zeros(shape=(3, 2, 3))
x3[0, ...] = x
x3[2, ...] = x
x3

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 2., 3.],
        [4., 5., 6.]]])

In [11]:
[0] + [1, 2, 33, 5]

[0, 1, 2, 33, 5]

In [12]:
np.zeros(5 * 2).shape

(10,)

In [13]:
np.zeros((5 * 2)).shape

(10,)

In [14]:
np.math.ceil(5/ 2)

3

In [15]:
l1 = np.zeros(10)
l1[2:5] = 5
l1

array([0., 0., 5., 5., 5., 0., 0., 0., 0., 0.])

In [16]:
dict1 = {1: 2, 3: 4, 0.2: 2}

In [17]:
len(dict1)

3

In [18]:
dict2 = dict.fromkeys([0.1, 0.2, 0.3])
dict2

{0.1: None, 0.2: None, 0.3: None}

In [19]:
np.zeros(2).shape

(2,)

In [20]:
np.repeat([1, 2], 3, axis=0)

array([1, 1, 1, 2, 2, 2])

In [23]:
np.tile([0, 1], 3)

array([0, 1, 0, 1, 0, 1])

In [24]:
1000 / 2

500.0

In [25]:
np.hstack([np.ndarray([1, 2]), np.ndarray([1, 2]), np.ndarray([1, 2]), np.ndarray([1, 2])]).shape

(1, 8)

In [26]:
np.hstack([[1, 2], [1, 2], [1, 2]])

array([1, 2, 1, 2, 1, 2])

In [27]:
x = np.array([3, 4, 5, 6, 7, 8, 9, 10])

In [28]:
y

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
np.sum(np.abs(y - x))

16

In [30]:
np.abs(y - x)

array([2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
x[:4]

array([3, 4, 5, 6])

In [32]:
x[-4:]

array([ 7,  8,  9, 10])

In [40]:
z = np.array([])
np.hstack([z, np.array([9, 10, 11])])

array([ 9., 10., 11.])

In [41]:
np.hstack([np.zeros(5), np.ones(3)])

array([0., 0., 0., 0., 0., 1., 1., 1.])

In [43]:
ids = np.array([3, 4])
x[ids]

array([6, 7])

In [53]:
s1 = np.random.seed()
s1