In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [16]:
t1 = torch.randn(3, 2, 3)
print(t1)
t1_mean = t1.mean(1)
print(t1_mean)
t2 = torch.mean(t1, 1)
print(t2)

tensor([[[ 1.5281,  1.7802,  0.8371],
         [-0.1232,  1.9599,  0.0790]],

        [[-0.0691,  0.2945, -0.1687],
         [-0.2039,  0.4257,  2.4525]],

        [[ 1.9294,  1.0868, -0.7715],
         [-0.9650, -0.8644,  0.5029]]])
tensor([[ 0.7024,  1.8700,  0.4580],
        [-0.1365,  0.3601,  1.1419],
        [ 0.4822,  0.1112, -0.1343]])
tensor([[ 0.7024,  1.8700,  0.4580],
        [-0.1365,  0.3601,  1.1419],
        [ 0.4822,  0.1112, -0.1343]])


In [11]:
# calculate mean of all numbers
(1.0324 + 0.1421 -0.8232-0.3505-0.6134-1.2448) /6
(-0.0319-0.9894-0.8067)/3

-0.6093333333333333

In [21]:
triplet_loss = nn.TripletMarginLoss(margin=1.0, p=2, eps=1e-7)
anchor = torch.randn(4, 100, 128)
positive = torch.randn(4, 100, 128)
negative = torch.randn(4, 100, 128)
output = triplet_loss(anchor, positive, negative)
output

tensor(1.1352)